<a href="https://colab.research.google.com/github/GabeMaldonado/UoL_Study_Materials/blob/main/2_1_Linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on linear algebra
## Instructions:
* Go through the notebook and complete the tasks. 
* Make sure you understand the examples given. If you need help, refer to the Essential readings or the documentation link provided, or go to the Topic 2 discussion forum. 
* When a question allows a free-form answer (e.g. what do you observe?), create a new markdown cell below and answer the question in the notebook. 
* Save your notebooks when you are done.
 
**Task 1:**
Go through the tutorial on Linear Algebra in Python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.
Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.


In [2]:
import numpy as np

#Code here - use code samples from link above

**Task 2:**
Create the following matrices:

$X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$ 

Then do the following:
1.	Multiply ```X``` with ```Y``` (```Z1=X*Y=XY```) and print the result. What do you observe? 
2.	Multiply ```X``` with ```Y``` transpose (```Z2=X*Y.T```) and print the result. What do you observe? 
3.	What can you tell about matrix ```Y```, given ```Z1``` and ```Z2```? 

In [3]:
#Code here

X = np.array([(2, 3, 4), (1, 2, 3)])
X

array([[2, 3, 4],
       [1, 2, 3]])

In [4]:
Y = np.array([(0, 1, 0), (1, 0, 0), (0, 0, 1)])
Y

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [11]:
Z1 = X.dot(Y)
Z1

array([[3, 2, 4],
       [2, 1, 3]])

In [13]:
Z2 = X.dot(Y.T)
Z2

array([[3, 2, 4],
       [2, 1, 3]])

**Task 3:** 
Create a 2x2 identity matrix ```I``` using the NumPy function ```eye(dim)``` $$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$


In [15]:
#Code here

I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

**Task 4:** 
1. Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2. Print the output.
3. What do you observe? 



In [16]:
x=np.array([2,3])
print(x)
#Code here
I.dot(x)

[2 3]


array([2., 3.])

**Task 5:**
1.	Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2.	Print the output.
3.	What do you observe? 


In [17]:
X=np.array([[2,3],[4,5]])
print(x)
#Code here
I.dot(X)

[2 3]


array([[2., 3.],
       [4., 5.]])

**Task 6:**
1. Multiply (using dot) matrix $X$ with the inverse matrix, $X^{-1}$ (use the NumPy function ```linalg.inv``` to do so): $XX^{-1}$
2. What do you observe? 




In [19]:
X=np.array([[1,2],[0,1]])
#Code here

X.dot(np.linalg.inv(X))


array([[1., 0.],
       [0., 1.]])