<a href="https://colab.research.google.com/github/GabeMaldonado/UoL_Study_Materials/blob/main/Linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on linear algebra
## Instructions:
* Go through the notebook and complete the tasks. 
* Make sure you understand the examples given. If you need help, refer to the Essential readings or the documentation link provided, or go to the Topic 2 discussion forum. 
* When a question allows a free-form answer (e.g. what do you observe?), create a new markdown cell below and answer the question in the notebook. 
* Save your notebooks when you are done.
 
**Task 1:**
Go through the tutorial on Linear Algebra in Python here: http://ml-cheatsheet.readthedocs.io/en/latest/linear_algebra.html.
Paste and run the code from the tutorial in the empty cell below (or create new empty cells below) to get more familiar with the material.


In [ ]:
import numpy as np

#Code here - use code samples from link above

In [ ]:
# Element-wise operations
y = np.array([1,2,3])
x = np.array([2,3,4])
print(y + x)
#[3, 5, 7]
print(y - x)
#= [-1, -1, -1]
print(y / x)
# = [.5, .67, .75]


[3 5 7]
[-1 -1 -1]
[0.5        0.66666667 0.75      ]


In [ ]:
# Dot Product
y = np.array([1,2,3])
x = np.array([2,3,4])
print(np.dot(y,x))

20


In [ ]:
# Hadamard Product
y = np.array([1,2,3])
x = np.array([2,3,4])
print(y * x )

[ 2  6 12]


In [ ]:
# Matrices

a = np.array([
 [1,2,3],
 [4,5,6]
])
a.shape == (2,3)
b = np.array([
 [1,2,3]
])
b.shape == (1,3)


True

In [ ]:
# Scalar Operations

# Addition
a = np.array(
[[1,2],
 [3,4]])
a + 1
[[2,3],
 [4,5]]

[[2, 3], [4, 5]]

In [ ]:
a = np.array([
 [1,2],
 [3,4]])
b = np.array([
 [1,2],
 [3,4]])

print(a + b)

#[[2, 4],
# [6, 8]]

print(a - b)
#[[0, 0],
#[0, 0]]

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [ ]:
a = np.array(
[[2,3],
 [2,3]])
b = np.array(
[[3,4],
 [5,6]])

# Uses python's multiply operator
a * b
#[[ 6, 12],
# [10, 18]]

array([[ 6, 12],
       [10, 18]])

In [ ]:
a = np.array([
   [1, 2],
   [3, 4]])

a.T
#[[1, 3],
# [2, 4]]

array([[1, 3],
       [2, 4]])

In [ ]:
a = np.array([
 [1, 2]
 ])
a.shape == (1,2)
b = np.array([
 [3, 4],
 [5, 6]
 ])
b.shape == (2,2)

# Multiply
mm = np.dot(a,b)
mm == [13, 16]
mm.shape == (1,2)

True

In [ ]:
a = np.array([
 [1],
 [2]
])
b = np.array([
 [3,4],
 [5,6]
])
c = np.array([
 [1,2]
])

# Same no. of rows
# Different no. of columns
# but a has one column so this works
a * b
[[ 3, 4],
 [10, 12]]

# Same no. of columns
# Different no. of rows
# but c has one row so this works
b * c
[[ 3, 8],
 [5, 12]]

# Different no. of columns
# Different no. of rows
# but both a and c meet the
# size 1 requirement rule
a + c
[[2, 3],
 [3, 4]]


[[2, 3], [3, 4]]

**Task 2:**
Create the following matrices:

$X=\begin{bmatrix} 2 & 3 & 4 \\ 1 & 2 &3 \end{bmatrix},Y=\begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 &0\\ 0 & 0 & 1 \end{bmatrix}$ 

Then do the following:
1.	Multiply ```X``` with ```Y``` (```Z1=X*Y=XY```) and print the result. What do you observe? 
2.	Multiply ```X``` with ```Y``` transpose (```Z2=X*Y.T```) and print the result. What do you observe? 
3.	What can you tell about matrix ```Y```, given ```Z1``` and ```Z2```? 

In [22]:
#Code here
X = np.array([[2, 3, 4], [1, 2, 3]])
X

array([[2, 3, 4],
       [1, 2, 3]])

In [23]:
Y = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
Y

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [26]:
Z1 = X.dot(Y)
Z1

array([[3, 2, 4],
       [2, 1, 3]])

In [27]:
Z2 = X.dot(Y.T)
Z2

array([[3, 2, 4],
       [2, 1, 3]])

**Task 3:** 
Create a 2x2 identity matrix ```I``` using the NumPy function ```eye(dim)``` $$ I=\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} $$


In [28]:
#Code here
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

**Task 4:** 
1. Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2. Print the output.
3. What do you observe? 



In [29]:
x=np.array([2,3])
print(x)
#Code here
I.dot(x)

[2 3]


array([2., 3.])

**Task 5:**
1.	Multiply (using dot) matrix ```I``` with the vector ```x``` defined below: $$Ix$$
2.	Print the output.
3.	What do you observe? 


In [31]:
X=np.array([[2,3],[4,5]])
print(X)
#Code here
I.dot(X)

[[2 3]
 [4 5]]


array([[2., 3.],
       [4., 5.]])

**Task 6:**
1. Multiply (using dot) matrix $X$ with the inverse matrix, $X^{-1}$ (use the NumPy function ```linalg.inv``` to do so): $XX^{-1}$
2. What do you observe? 




In [32]:
X=np.array([[1,2],[0,1]])
#Code here
X.dot(np.linalg.inv(X))


array([[1., 0.],
       [0., 1.]])